# Database Configuration for Order Service
spring.datasource.url=jdbc:mariadb://localhost:3306/orderstock
spring.datasource.username=deepak
spring.datasource.password=deepak

# Server Port
server.port=8084

# Feign Client / Routing Configurations to locate Stock Service
stock-service.url=http://localhost:8082
